version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ../database/mongo-volume:/data/db
      - ../database/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"

  backend:
    build: ../backend
    container_name: backend
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
